version: '3'

services:
  php:
    build: .
    container_name: the-asdev-link-manager
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: asdev-phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONNECTION}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    container_name: ${DB_HOST}
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - ./links.sql:/docker-entrypoint-initdb.d/links.sql
      - /var/lib/mysql
